### ISSUE TITLE
request for data files

### ISSUE THREAD

**Issue by cloudflyCF** [xxh0523/Py_PSNODE#1]
作者您好，可以提供一下data文件夹吗，显示在 '/home/xiaotannan/pythonPS/00saved_results/samples/avr_1/1000_gen33_4000_nolimit_samples_avr_1_new/'
这个路径下面的

In English:
Can you provide data files located at '/home/xiaotannan/pythonPS/00saved_results/samples/avr_1/1000_gen33_4000_nolimit_samples_avr_1_new/'?

**Comment by xxh0523** [comment]
> 作者您好，可以提供一下data文件夹吗，显示在 '/home/xiaotannan/pythonPS/00saved_results/samples/avr_1/1000_gen33_4000_nolimit_samples_avr_1_new/' 这个路径下面的

First of all, thank you for your attention to our code. 
Secondly, I hope that we can communicate in English so that all other users can understand this issue.

I have uploaded a sample data file to Baidu web storage. The web link is as follows.
URL: https://pan.baidu.com/s/1P24h0AQqNS9SAwG1K4wW6g 
Code：tiiy

**Comment by cloudflyCF** [comment]
Thank you very much for providing the data.

> > 作者您好，可以提供一下data文件夹吗，显示在 '/home/xiaotannan/pythonPS/00saved_results/samples/avr_1/1000_gen33_4000_nolimit_samples_avr_1_new/' 这个路径下面的
> 
> First of all, thank you for your attention to our code. Secondly, I hope that we can communicate in English so that all other users can understand this issue.
> 
> I have uploaded a sample data file to Baidu web storage. The web link is as follows. URL: https://pan.baidu.com/s/1P24h0AQqNS9SAwG1K4wW6g Code：tiiy
